/* This file was generated by the Hex-Rays decompiler version 9.0.0.240807.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

char leng[5] = "1025"; // weak

//----- (0000000000001239) ----------------------------------------------------
int sndmsg(char msg[1024], int port)
{
  size_t v3;               // rax
  int fd;                  // [rsp+18h] [rbp-428h]
  struct sockaddr addr; // [rsp+20h] [rbp-420h] BYREF
  char dest[1032];         // [rsp+30h] [rbp-410h] BYREF

  strncpy(dest, msg, 1024);
  dest[1024] = 0;
  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP);
  if (fd >= 0)
  {
    addr.sa_family = AF_INET;
    *addr.sa_data = htons(port);
    if (inet_pton(AF_INET, "127.0.0.1", &addr.sa_data[2]) > 0)
    {
      if (connect(fd, &addr, sizeof(addr)) >= 0)
      {
        send(fd, leng, sizeof(leng), 0);
        v3 = strlen(dest);
        send(fd, dest, v3, 0);
        close(fd);
        return 0;
      }
      else
      {
        puts("\nConnection Failed ");
        return -1;
      }
    }
    else
    {
      puts("\nInvalid address/ Address not supported ");
      return -1;
    }
  }
  else
  {
    puts("\n Socket creation error ");
    return -1;
  }
}
