/* This file was generated by the Hex-Rays decompiler version 9.0.0.240807.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

struct sockaddr address;
int server_fd[4];
socklen_t addrlen[2];

//----- (0000000000001279) ----------------------------------------------------
int startserver(uint16_t a1)
{
  int result; // eax
  int optval; // [rsp+1Ch] [rbp-4h] BYREF

  optval = 1;
  server_fd[0] = socket(2, 1, 0);
  if (server_fd[0] < 0)
  {
    perror("socket failed");
    exit(1);
  }
  if (setsockopt(server_fd[0], 1, 15, &optval, 4u))
  {
    perror("setsockopt");
    exit(1);
  }
  address.sa_family = 2;
  address.sa_data[2] = 0;
  *address.sa_data = htons(a1);
  if (bind(server_fd[0], &address, 16) < 0)
  {
    perror("bind failed");
    exit(1);
  }
  result = listen(server_fd[0], 3);
  if (result < 0)
  {
    perror("listen");
    exit(1);
  }
  return result;
}
// 40A0: using guessed type int server_fd[4];
// 40B0: using guessed type struct sockaddr address;

//----- (00000000000013AD) ----------------------------------------------------
int getmsg(char *a1)
{
  char buf[1024] = {0};
  
  int new_socket = accept(server_fd[0], &address, addrlen);
  if (new_socket < 0)
  {
    perror("accept");
    exit(1);
  }
  ssize_t valread = read(new_socket, buf, 5);
  int v4 = atoi((const char *)buf);
  valread = read(new_socket, buf, v4);
  close(new_socket);
  strcpy(a1, (const char *)buf);
  return 0;
}
// 4080: using guessed type socklen_t addrlen[2];
// 40A0: using guessed type int server_fd[4];
// 40B0: using guessed type struct sockaddr address;

//----- (00000000000014DB) ----------------------------------------------------
int stopserver()
{
  close(server_fd[0]);
  return 0;
}
// 14DB: using guessed type __int64 stopserver();
// 40A0: using guessed type int server_fd[4];
